//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychoTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int Question_id { get; set; }
        public string Content { get; set; }
        public Nullable<int> Id_test { get; set; }
        public Nullable<int> Id_answer { get; set; }
    
        public virtual Answers Answers { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
